version = 1

[merge]
automerge_label = "ğŸš€ automerge"

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["renovate"]

[update]
autoupdate_label = "â™»ï¸ autoupdate"

[approve]
auto_approve_usernames = ["rennovate", "tundera"]